### ISSUE TITLE
Это нотифер в телеграм

### ISSUE THREAD

**Issue by rainautumn** [CapitanCode/rutracker_notifier#1]
Но почему именно такое решение? Ведь можно было выннсти в notify.  На десктор и на телефон так-же. Да, кода больше бы вышло, но зависимости от телеграмма тащить это жирненько. Нет?

**Comment by CapitanCode** [comment]
>Но почему именно такое решение?
Телеграм стал по сути стандартом в индустрии мессенджеров в мире гиков и кодеров. Одной строчкой можно добавить его суппорт с свой проект. Если есть желание добавить другие сервисы, то я с радостью приму пул реквест.

**Comment by rainautumn** [comment]
>стандартом
не слышал об этом. Он требует номера телефона которые не у всех есть
>другие сервисы
Знал бы Python я бы интегрировал сервис в AutumnDock

**Comment by devm-ru** [comment]
@rainautumn на самом деле очень удобно. У меня телеграм на разных устройствах. И таким образом, оповещение приходит всем устройствам. Таким образом можно перейти в него из оповещения (это будет быстро, так как он всегда запущен), и тыкнуть на линк из оповещения. Так же, ещё одна фишка добавляется - история обновлений.

**Comment by rainautumn** [comment]
@devm-ru но телеграмм не коссплатформенный. у меня он сможет только на ноутбуке жить. и если быть адекватом то оповещения должны уходить в апи. как пример

**Comment by devm-ru** [comment]
@rainautumn 
> не коссплатформенный

ты шутишь? 
![Imgur](http://i.imgur.com/mvqpetX.png)
Возможно ты прав, говоря про зависимость в виде телеграм-бота, но она не так уж велика

**Comment by rainautumn** [comment]
Ни BSD ни симбиана ни блекбери ни оракловского творения, ни хромооси нет (токс умеет воистину все pc, вотсап все мобильники). Это псевдокросплатформенность. + нуднейшая регистрация. web версия типо кросплатформенна?  а чем тогда всё это перечисленное отличается от нотифа в твиттер? 6 платформ в 2016ом это не кросплатформенность. я про колибри и миниксы ещё промолчал.
